Do not force ExDoc as a compile time dependency on users.
Without this change, I am getting a compile error:

```
== Compilation error on file lib/mix/tasks/update_readme.ex ==
** (CompileError) lib/mix/tasks/update_readme.ex:28: ExDoc.FunctionNode.__struct__/0 is undefined, cannot expand struct ExDoc.FunctionNode
    (stdlib) lists.erl:1353: :lists.mapfoldl/3
```

While it is a bit ugly to pattern match on the `__struct__` key, it
allows us to pattern match on the struct without requiring its definition
to be present at compile time, so that users no longer need ex_doc.